name: Build and Publish JAR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn clean install

      - name: Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOL
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>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</password>
              </server>
            </servers>
          </settings>
          EOL

      - name: Publish to GitHub Packages
        run: mvn deploy --settings ~/.m2/settings.xml
        env:
          GITHUB_TOKEN: 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

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-lib-jar
          path: target/*.jar
