name: Build and Publish JAR
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: github 
          settings-path: ${{ github.workspace }}
 
      - name: Build with Maven
        run: mvn clean install
 
      - name: Publish to GitHub Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
 
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-lib-jar
          path: target/*.jar

